apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    redeploy-timestamp: "{{ timestamp }}" 
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: viswanadh7/multi-frontend:v2.0.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
  type: LoadBalancer