apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        # Route /api requests to backend with rewrite
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend
              port:
                number: 3000

        # Route everything else directly to frontend (no rewrite)
        - path: /.*    # matches everything else including static assets
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend
              port:
                number: 80
